version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      # TODO: Move into env file
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
